### ISSUE TITLE
open a .pl

### ISSUE THREAD

**Issue by donno2048** [radiac/python-perl#4]
can I use it somehow to do something like that?
in test.pl:
```perl
use strict;
use warnings;
print "this is a test";
```
in python:
```python
import perl
perl.exec(open('test.pl','r').read())
```
and get the output:
```
this is a test
```

**Comment by rgson** [comment]
You want `subprocess` for that.
```py
import subprocess
subprocess.run(['perl', 'test.pl'])
```

**Comment by donno2048** [comment]
I know that, but I want to be able to do inputs outputs etc.

**Comment by rgson** [comment]
`subprocess` does input/output, too. There's `PIPE` to control stdin/out/err, and if `run` doesn't cut it there's `Popen`.

Regardless, the answer is "no", this module won't help you achieve what you want. Its features are regex-related; It's not an actual Perl interpreter.

**Comment by donno2048** [comment]
Thanks

**Comment by radiac** [comment]
Thanks for the interest, but as rgson says, this library is more about bringing some of the highlights of perl into python, so although I may add some more functionality at some point, unless someone contributes a significant amount of code this project will never be able to interpret a full perl script.

To illustrate rgson's comment about subprocess and PIPE this may help:
```
import subprocess
process = subprocess.Popen(["perl", "test.pl"], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
process.stdin.write("input\n")
output = process.stdout.readline()
```
